const programs = [
  {
    key: 'KH50_001',
    name: {
      fi: 'Matemaattisten tieteiden kandiohjelma',
      en: "Bachelor's Programme in Mathematical Sciences",
      sv: 'Kandidatsprogrammet i matematiska vetenskaper',
    },
    level: 'bachelor',
    companionFaculties: [],
    international: false,
  },
  {
    key: 'KH50_002',
    name: {
      fi: 'Fysikaalisten tieteiden kandiohjelma',
      en: "Bachelor's Programme in Physical Sciences",
      sv: 'Kandidatprogrammet i fysikaliska vetenskaper',
    },
    level: 'bachelor',
    companionFaculties: [],
    international: false,
  },
  {
    key: 'KH50_003',
    name: {
      fi: 'Kemian kandiohjelma',
      en: "Bachelor's Programme in Chemistry",
      sv: 'Kandidatprogrammet i kemi',
    },
    level: 'bachelor',
    companionFaculties: [],
    international: false,
  },
  {
    key: 'KH50_004',
    name: {
      fi: 'Matematiikan, fysiikan ja kemian opettajan kandiohjelma',
      en: "Bachelor's Programme for Teachers of Mathematics, Physics and Chemistry",
      sv: 'Kandidatprogrammet för ämneslärare i matematik, fysik och kemi',
    },
    level: 'bachelor',
    companionFaculties: [],
    international: false,
  },
  {
    key: 'KH50_005',
    name: {
      fi: 'Tietojenkäsittelytieteen kandiohjelma',
      en: "Bachelor's Programme in Computer Science",
      sv: 'Kandidatprogrammet i datavetenskap',
    },
    level: 'bachelor',
    companionFaculties: [],
    international: false,
  },
  {
    key: 'KH50_007',
    name: {
      fi: 'Maantieteen kandiohjelma',
      en: "Bachelor's Programme in Geography",
      sv: 'Kandidatprogrammet i geografi',
    },
    level: 'bachelor',
    companionFaculties: [],
    international: false,
  },
  {
    key: 'KH50_008',
    name: {
      en: 'Bachelor’s Programme in Science',
      fi: 'Luonnontieteiden kandiohjelma',
      sv: 'Kandidatprogrammet i naturvetenskaper',
    },
    level: 'bachelor',
    companionFaculties: [],
    international: false,
  },
  {
    key: 'KH50_006',
    name: {
      fi: 'Geotieteiden kandiohjelma',
      en: "Bachelor's Programme in Geosciences",
      sv: 'Kandidatsprogrammet i geovetenskap',
    },
    level: 'bachelor',
    companionFaculties: [],
    international: false,
  },
  {
    key: 'MH50_001',
    name: {
      fi: 'Matematiikan ja tilastotieteen maisteriohjelma',
      en: "Master's Programme in Mathematics and Statistics",
      sv: 'Magisterprogrammet i matematik och statistik',
    },
    level: 'master',
    companionFaculties: ['valtiotieteellinen'],
    international: true,
  },
  {
    key: 'MH50_002',
    name: {
      fi: 'Life Science Informatics -maisteriohjelma',
      en: "Master's Programme in Life Science Informatics",
      sv: 'Magisterprogrammet i Life Science Informatics',
    },
    level: 'master',
    companionFaculties: ['bio- ja ympäristötieteellinen'],
    international: true,
  },
  {
    key: 'MH50_003',
    name: {
      fi: 'Teoreettisten ja laskennallisten menetelmien maisteriohjelma',
      en: "Master's Programme in Theoretical and Computational Methods",
      sv: 'Magisterprogrammet i teoretiska och beräkningsmetoder',
    },
    level: 'master',
    companionFaculties: [],
    international: true,
  },
  {
    key: 'MH50_004',
    name: {
      fi: 'Alkeishiukkasfysiikan ja astrofysikaalisten tieteiden maisteriohjelma',
      en: "Master's Programme in Particle Physics and Astrophysical Sciences",
      sv: 'Magisterprogrammet i elementarpartikelfysik och astrofysikaliska vetenskaper',
    },
    level: 'master',
    companionFaculties: [],
    international: true,
  },
  {
    key: 'MH50_005',
    name: {
      fi: 'Materiaalitutkimuksen maisteriohjelma',
      en: "Master's Programme in Materials Research",
      sv: 'Magisterprogrammet i materialforskning',
    },
    level: 'master',
    companionFaculties: [],
    international: true,
  },
  {
    key: 'MH50_006',
    name: {
      fi: 'Ilmakehätieteiden maisteriohjelma',
      en: "Master's Programme in Atmospheric Sciences",
      sv: 'Magisterprogrammet i atmosfärsvetenskaper',
    },
    level: 'master',
    companionFaculties: ['maatalous-metsätieteellinen'],
    international: true,
  },
  {
    key: 'MH50_007',
    name: {
      fi: 'Kemian ja molekyylitieteiden maisteriohjelma',
      en: "Master's Programme in Chemistry and Molecular Sciences",
      sv: 'Magisterprogrammet i kemi och molekylära vetenskaper',
    },
    level: 'master',
    companionFaculties: [],
    international: true,
  },
  {
    key: 'MH50_008',
    name: {
      fi: 'Matematiikan, fysiikan ja kemian opettajan maisteriohjelma',
      en: "Master's Programme for Teachers of Mathematics, Physics and Chemistry",
      sv: 'Magisterprogrammet för ämneslärare i matematik, fysik och kemi',
    },
    level: 'master',
    companionFaculties: [],
    international: false,
  },
  {
    key: 'MH50_009',
    name: {
      fi: 'Tietojenkäsittelytieteen maisteriohjelma',
      en: "Master's Programme in Computer Science",
      sv: 'Magisterprogrammet i datavetenskap',
    },
    level: 'master',
    companionFaculties: [],
    international: true,
  },
  {
    key: 'MH50_010',
    name: {
      fi: 'Datatieteen maisteriohjelma',
      en: "Master's Programme in Data Science",
      sv: 'Magisterprogrammet i data science',
    },
    level: 'master',
    companionFaculties: [],
    international: true,
  },
  {
    key: 'MH50_011',
    name: {
      fi: 'Geologian ja geofysiikan maisteriohjelma',
      en: "Master's Programme in Geology and Geophysics",
      sv: 'Magisterprogrammet i geologi och geofysik',
    },
    level: 'master',
    companionFaculties: [],
    international: true,
  },
  {
    key: 'MH50_012',
    name: {
      fi: 'Maantieteen maisteriohjelma',
      en: "Master's Programme in Geography",
      sv: 'Magisterprogrammet i geografi',
    },
    level: 'master',
    companionFaculties: [],
    international: true,
  },
  {
    key: 'MH50_013',
    name: {
      fi: 'Kaupunkitutkimuksen ja suunnittelun maisteriohjelma',
      en: "Master's Programme in Urban Studies and Planning",
      sv: 'Magisterprogrammet i urbana studier och planering',
    },
    level: 'master',
    companionFaculties: [
      'bio- ja ympäristötieteellinen',
      'valtiotieteellinen',
      'humanistinen',
    ],
    international: true,
  },
  {
    key: 'MH50_014',
    name: {
      fi: 'Nordic Master Programme in Environmental Changes at Higher Latitudes',
      en: 'Nordic Master Programme in Environmental Changes at Higher Latitudes',
      sv: 'Nordic Master Programme in Environmental Changes at Higher Latitudes',
    },
    level: 'master',
    companionFaculties: [],
    international: true,
  },
  {
    key: 'T923102',
    name: {
      fi: 'Geotieteiden tohtoriohjelma',
      en: 'Doctoral Programme in Geosciences',
      sv: 'Doktorandprogrammet i geovetenskap',
    },
    level: 'doctoral',
    companionFaculties: ['humanistinen'],
    international: false,
  },
  {
    key: 'T923103',
    name: {
      fi: 'Ilmakehätieteiden tohtoriohjelma',
      en: 'Doctoral Programme in Atmospheric Sciences',
      sv: 'Doktorandprogrammet i atmosfärvetenskap',
    },
    level: 'doctoral',
    companionFaculties: ['maatalous-metsätieteellinen'],
    international: false,
  },
  {
    key: 'T923104',
    name: {
      fi: 'Kemian ja molekyylitutkimuksen tohtoriohjelma',
      en: 'Doctoral Programme in Chemistry and Molecular Research',
      sv: 'Doktorandprogrammet i kemi och molekylära vetenskaper',
    },
    level: 'doctoral',
    companionFaculties: ['farmasia'],
    international: false,
  },
  {
    key: 'T923105',
    name: {
      fi: 'Matematiikan ja tilastotieteen tohtoriohjelma',
      en: 'Doctoral Programme in Mathematics and Statistics',
      sv: 'Doktorandprogrammet i matematik och statistik',
    },
    level: 'doctoral',
    companionFaculties: [],
    international: false,
  },
  {
    key: 'T923106',
    name: {
      fi: 'Materiaalitutkimuksen ja nanotieteiden tohtoriohjelma',
      en: 'Doctoral Programme in Materials Research and Nanoscience',
      sv: 'Doktorandprogrammet i materialforskning och nanovetenskap',
    },
    level: 'doctoral',
    companionFaculties: ['farmasia'],
    international: false,
  },
  {
    key: 'T923107',
    name: {
      fi: 'Tietojenkäsittelytieteen tohtoriohjelma',
      en: 'Doctoral Programme in Computer Science',
      sv: 'Doktorandprogrammet i datavetenskap',
    },
    level: 'doctoral',
    companionFaculties: [],
    international: false,
  },
  {
    key: 'T923101',
    name: {
      fi: 'Alkeishiukkasfysiikan ja maailmankaikkeuden tutkimuksen tohtoriohjelma',
      en: 'Doctoral Programme in Particle Physics and Universe Sciences',
      sv: 'Doktorandprogrammet i elementarpartikelfysik och kosmologi',
    },
    level: 'doctoral',
    companionFaculties: [],
    international: false,
  },
]

export default programs
