version: '3.5'

services:
  app:
    build:
      context: .
      args:
        - E2E=true
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    command: ['npm', 'run', 'start:test']
    ports:
      - 8000:8000
    container_name: grapa_test

  db:
    image: postgres:15.8
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    container_name: grapa_test_db

  redis:
    image: redis:7-alpine
    container_name: grapa_test_redis
