services:
  app:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    image: grapa_dev
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./:/opt/app-root/src
    ports:
      - 3000:3000
      - 8000:8000
    container_name: grapa_dev
    networks:
      - grapa_internal

  db:
    image: postgres:15.10
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/data
    container_name: grapa_db
    networks:
      - grapa_internal


  redis:
    image: redis:8-alpine
    container_name: grapa_redis
    networks:
      - grapa_internal


  # login.toska.localhost:
  #   image: hy-oidc-emu
  #   ports: 
  #     - 3001:3001
  #   volumes:
  #     - ./oidc_emu/accounts.json:/opt/app-root/src/accounts.json
  #     - ./oidc_emu/configuration.json:/opt/app-root/src/configuration.json
  #    networks:
  #      - grapa_internal

volumes:
  pg_data:

networks:
  grapa_internal:
    driver: bridge