name: Deploy to production

on:
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: grapa
          tags: production ${{ github.sha }}
          containerfiles: |
            ./Dockerfile
          build-args: |
            GIT_SHA=${{ github.sha }}

      - name: Push to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/toska
          username: toska+github
          password: ${{ secrets.QUAY_IO_TOKEN }}

  sentry-release:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - uses: actions/checkout@v3

      - name: Pull image and create a container
        run: docker create --name grapa quay.io/toska/grapa:production

      - name: Copy assets from the container
        run: docker cp grapa:/opt/app-root/src ./app

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_URL: https://toska.cs.helsinki.fi/
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_TOKEN }}
          SENTRY_ORG: toska
          SENTRY_PROJECT: grapa
        with:
          environment: production
          set_commits: 'skip'
          sourcemaps: ./app
          url_prefix: '~/app'
