name: Test and deploy to staging in local

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: runner-scaleset-docker
    # runs-on: runner-scaleset #tämän pitää olla tarkalleen tämä että oikea runner löytyy organisaation alta.
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24.x'
          cache: 'npm'
      
      - run: npm ci --no-audit --no-fund

      # - run: echo $PATH

      # - run: ls /bin

      # - run: which docker

      # - run: which podman

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build
        uses: docker/build-push-action@v7
        with:
          file: Dockerfile
          push: false
          tags: grapa:staging-local
          build-args: |
            BASE_PATH= 
            GIT_SHA=${{ github.sha }}
            STAGING=true
            E2E=false

      # - name: Build image docker
      #   id: build-image
      #   env:
      #     BASE_PATH: 
      #     GIT_SHA: ${{ github.sha }}
      #     STAGING: true
      #     E2E: false
      #   run: docker build --tag "grapa:staging-local" --label "org.opencontainers.image.revision=$GIT_SHA" --label "org.opencontainers.image.created=$(date -u +%Y-%m-%dT%H:%M:%SZ)" .

      # - name: Build image
      #   id: build-image
      #   uses: redhat-actions/buildah-build@v3
      #   with:
      #     image: grapa
      #     tags: staging-local ${{ github.sha }}
      #     containerfiles: |
      #       ./Dockerfile
      #     build-args: |
      #       BASE_PATH=
      #       GIT_SHA=${{ github.sha }}
      #       STAGING=true
      #       E2E=false
      #     # ulimit 4096 is required for the buildah to work
      #     # otherwise throws error "Too many open files"
      #     extra-args: --ulimit nofile=4096:4096


      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
      - run: npm run test:front
      - run: npm run test:integration

      # - name: Push to registry.version.helsinki.fi
      #   uses: redhat-actions/push-to-registry@v3
      #   with:
      #     image: ${{ steps.build-image.outputs.image }}
      #     tags: ${{ steps.build-image.outputs.tags }}
      #     registry: registry.version.helsinki.fi/toska/openshift/kontit/
      #     username: kontit
      #     password: ${{ secrets.VERSION_PUSH_SECRET }}
